version: "3.9"
services:
  gtsam-base:
    image: gtsam-base:noetic
    build:
      context: .
      dockerfile: Dockerfile.gtsam.noetic

  sc-lio:
    image: slam-sc-lio:noetic
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gtsam-base
    network_mode: host
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/santiago/Downloads/mulran/:/data/mulran
      - ./output:/output
      - ./run_eval_ros1.sh:/run_eval_ros1.sh
      - ./run_sweep.sh:/run_sweep.sh
      - ./odom_to_tum.py:/odom_to_tum.py
      - ./helpers/:/helpers
      - ./record_mulran_input.sh:/record_mulran_input.sh
      - ./extract-trajectory:/extract-trajectory
